export type ProductData = {
  id: number;
  header: string;
  name: string;
  stock: number;
  categoria: string;
  status: string;
  price: number;
  supplier: string;
  lastUpdated: string;
};

export const productsData: ProductData[] = [
  {
    id: 1,
    header: "Componente Electrónico Premium",
    name: "piece",
    stock: 40,
    categoria: "Electrónica",
    status: "Done",
    price: 45.99,
    supplier: "TechSupply Co.",
    lastUpdated: "2025-10-08",
  },
  {
    id: 2,
    header: "Motor Paso a Paso NEMA 17",
    name: "motor",
    stock: 25,
    categoria: "Robótica",
    status: "In Progress",
    price: 89.5,
    supplier: "RoboParts Ltd.",
    lastUpdated: "2025-10-07",
  },
  {
    id: 3,
    header: "Sensor de Temperatura DS18B20",
    name: "sensor",
    stock: 120,
    categoria: "Sensores",
    status: "Done",
    price: 9.99,
    supplier: "ElectroWorld",
    lastUpdated: "2025-10-06",
  },
  {
    id: 4,
    header: "Pantalla OLED 0.96'' Azul",
    name: "display",
    stock: 80,
    categoria: "Electrónica",
    status: "Pending",
    price: 12.75,
    supplier: "VisionTech",
    lastUpdated: "2025-10-05",
  },
  {
    id: 5,
    header: "Placa Arduino Mega 2560",
    name: "board",
    stock: 30,
    categoria: "Microcontroladores",
    status: "Done",
    price: 58.0,
    supplier: "MakerZone",
    lastUpdated: "2025-10-08",
  },
  {
    id: 6,
    header: "Cable Dupont Macho-Macho (40 pzs)",
    name: "cable",
    stock: 200,
    categoria: "Accesorios",
    status: "Done",
    price: 5.49,
    supplier: "WireHouse",
    lastUpdated: "2025-10-04",
  },
  {
    id: 7,
    header: "Resistencias 10kΩ (100 pzs)",
    name: "resistor",
    stock: 500,
    categoria: "Componentes",
    status: "Done",
    price: 7.25,
    supplier: "TechParts Global",
    lastUpdated: "2025-10-02",
  },
  {
    id: 8,
    header: "Módulo WiFi ESP8266",
    name: "module",
    stock: 60,
    categoria: "Comunicaciones",
    status: "In Progress",
    price: 14.9,
    supplier: "IoT Supply",
    lastUpdated: "2025-10-07",
  },
  {
    id: 9,
    header: "Servo Motor SG90 9g",
    name: "servo",
    stock: 150,
    categoria: "Robótica",
    status: "Done",
    price: 8.99,
    supplier: "RoboZone",
    lastUpdated: "2025-10-03",
  },
  {
    id: 10,
    header: "Fuente de Poder 12V 5A",
    name: "psu",
    stock: 35,
    categoria: "Energía",
    status: "Pending",
    price: 25.99,
    supplier: "VoltMaster",
    lastUpdated: "2025-10-08",
  },
  {
    id: 11,
    header: "Sensor Ultrasonido HC-SR04",
    name: "ultrasonic",
    stock: 95,
    categoria: "Sensores",
    status: "Done",
    price: 11.5,
    supplier: "SmartParts",
    lastUpdated: "2025-10-05",
  },
  {
    id: 12,
    header: "Batería de Litio 18650 3.7V 2600mAh",
    name: "battery",
    stock: 75,
    categoria: "Energía",
    status: "In Progress",
    price: 18.5,
    supplier: "PowerCell Inc.",
    lastUpdated: "2025-10-06",
  },
  {
    id: 13,
    header: "Módulo Relé 2 Canales 5V",
    name: "relay",
    stock: 130,
    categoria: "Automatización",
    status: "Done",
    price: 10.25,
    supplier: "ControlTech",
    lastUpdated: "2025-10-02",
  },
  {
    id: 14,
    header: "Raspberry Pi 4 8GB",
    name: "computer",
    stock: 10,
    categoria: "Microcontroladores",
    status: "Pending",
    price: 105.9,
    supplier: "PiStore",
    lastUpdated: "2025-10-08",
  },
  {
    id: 15,
    header: "Sensor de Movimiento PIR",
    name: "motion",
    stock: 70,
    categoria: "Sensores",
    status: "Done",
    price: 8.75,
    supplier: "SensePro",
    lastUpdated: "2025-10-01",
  },
  {
    id: 16,
    header: "Cable USB Tipo-C a Micro-B",
    name: "usb",
    stock: 90,
    categoria: "Accesorios",
    status: "Done",
    price: 6.5,
    supplier: "WireHouse",
    lastUpdated: "2025-10-06",
  },
  {
    id: 17,
    header: "Módulo Bluetooth HC-05",
    name: "bluetooth",
    stock: 55,
    categoria: "Comunicaciones",
    status: "In Progress",
    price: 13.99,
    supplier: "IoT Supply",
    lastUpdated: "2025-10-07",
  },
  {
    id: 18,
    header: "Kit de Protoboard + Jumpers",
    name: "kit",
    stock: 40,
    categoria: "Accesorios",
    status: "Done",
    price: 15.9,
    supplier: "MakerZone",
    lastUpdated: "2025-10-05",
  },
  {
    id: 19,
    header: "Cámara Raspberry Pi HQ",
    name: "camera",
    stock: 12,
    categoria: "Visión",
    status: "Pending",
    price: 75.0,
    supplier: "VisionTech",
    lastUpdated: "2025-10-08",
  },
  {
    id: 20,
    header: "Módulo GPS Neo-6M",
    name: "gps",
    stock: 25,
    categoria: "Comunicaciones",
    status: "Done",
    price: 22.5,
    supplier: "GeoTrack Systems",
    lastUpdated: "2025-10-06",
  },
  {
    id: 21,
    header: "Kit de Herramientas de Precisión",
    name: "tools",
    stock: 50,
    categoria: "Mantenimiento",
    status: "Done",
    price: 34.99,
    supplier: "FixIt Pro",
    lastUpdated: "2025-10-04",
  },
];
